site:
  title: Accordion Manual

content:
  sources:
  - url: https://github.com/dawoong/test-antora.git
    branched: [stephengold]

ui:
  bundle:
    url: https://github.com/asciidoctor/asciidoctor-docs-ui/releases/download/prod-213/ui-bundle.zip
    snapshot: true
