site:
  title: Accordion Manual

content:
  sources:
  - url: https://github.com/dawoong/test-antora.git
    branched: [master]

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

